#!/bin/bash

# Blackmoon Database Backup Script
# Excludes Payload CMS system tables (can be regenerated automatically)
# Includes: Your data (users, media, hexImages, maptiles, etc.)
# Excludes: payload_locked_documents, payload_preferences, payload_migrations

printf -v date '%(%Y%m%d_%H%M%S)T\n' -1
now=$(date +%F_%H-%M-%S)
echo "Starting backup at: ${now}"

# Create temporary directory for backup files
TEMP_DIR="/tmp/blackmoon_backup_${now}"
mkdir -p "${TEMP_DIR}"

# Dump PostgreSQL database (excluding Payload system tables)
echo "Dumping PostgreSQL database (excluding system tables)..."
docker compose exec -T postgres pg_dump -U blackmoon blackmoon \
  --exclude-table="payload_locked_documents" \
  --exclude-table="payload_preferences" \
  --exclude-table="payload_migrations" \
  --exclude-table="payload_reviews" > "${TEMP_DIR}/blackmoon.sql"

if [ $? -eq 0 ]; then
    echo "✅ Database dump successful"
    # Show size of dump
    du -h "${TEMP_DIR}/blackmoon.sql"
else
    echo "❌ Database dump failed"
    rm -rf "${TEMP_DIR}"
    exit 1
fi

# Copy media directory (includes original images and hex versions)
echo "Copying media files..."
if [ -d "/node/blackmoon/media" ]; then
    cp -r /node/blackmoon/media "${TEMP_DIR}/"
    echo "✅ Media files copied"
else
    echo "⚠️  Media directory not found, skipping"
fi

# Note: hex-images directory is no longer used (hex images are now in media/)
# Kept for backward compatibility during transition
if [ -d "/node/blackmoon/hex-images" ]; then
    echo "Copying legacy hex-images directory..."
    cp -r /node/blackmoon/hex-images "${TEMP_DIR}/"
fi

# Create zip archive
echo "Creating backup archive..."
cd "${TEMP_DIR}"
zip -r "/mnt/HC_Volume_102781745/blackmoon/blackmoon_${now}.zip" .

if [ $? -eq 0 ]; then
    echo "✅ Archive created successfully"
    du -h "/mnt/HC_Volume_102781745/blackmoon/blackmoon_${now}.zip"
else
    echo "❌ Archive creation failed"
    cd /
    rm -rf "${TEMP_DIR}"
    exit 1
fi

# Cleanup temp directory
cd /
rm -rf "${TEMP_DIR}"

echo ""
echo "✅ Backup complete: /mnt/HC_Volume_102781745/blackmoon/blackmoon_${now}.zip"
echo ""
echo "Excluded Payload system tables:"
echo "  - payload_locked_documents (document locking state)"
echo "  - payload_preferences (user UI preferences)"
echo "  - payload_migrations (migration history)"
echo "  - payload_reviews (draft reviews)"
echo ""
echo "These are auto-generated by Payload and don't need to be backed up."

# Optional: Keep only last 7 backups
# Uncomment to enable automatic cleanup of old backups
#echo "Cleaning up old backups (keeping last 7 days)..."
#find /mnt/HC_Volume_102781745/blackmoon/ -name "blackmoon_*.zip" -mtime +7 -delete
#echo "✅ Cleanup complete"
